title: Westley Holmes
logo: https://media.licdn.com/dms/image/v2/D4E03AQGQqap70njXxA/profile-displayphoto-shrink_800_800/B4EZRnmHX_GgAc-/0/1736904832841?e=1743033600&v=beta&t=hgLoqd_eM7m_EhmT0oeLwgKn2awVj4RyDA4h2xTKNOQ
description: 206-739-7557, westleyholmesbusiness@gmail.com, www.linkedin.com/in/westley-holmes-98722925a
#show_dowloads: True
theme: jekyll-theme-minimal
