title: Westley Holmes
logo: /assets/circleheadshot.jpg
description: 206-739-7557 westleyholmesbusiness@gmail.com www.linkedin.com/in/westley-holmes-98722925a
#show_dowloads: True
theme: jekyll-theme-minimal
